# Generated by Django 3.2.5 on 2021-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Fruits'), ('BW', ' Vegetables')], max_length=2),
        ),
    ]
